language: python
python:
  - "2.6"
install:
  - echo "Aqui se instalan las dependencia"
  - pip install --upgrade pip
  - pip install virtualenv
 
before_script:
  - echo "Antes de ejecutar un script"

script:
  - echo "Pruebas unitarias de Calculadora"
  - python Test*.py
  - echo "Finalizar"

notifications:
  - email: false